### ISSUE TITLE
Hey hey!

### ISSUE THREAD

**Issue by michaelborn** [scotteuser/passwordhaveibeenpwned#1]
Was browsing the [marketplace](https://market.bolt.cm/), saw that this extension had been published yesterday, and thought it looked cool enough to check out.

No suggestions in terms of code. I am still yet to write my first Bolt extension.

For the [extension page itself](https://market.bolt.cm/view/scotteuser/passwordhaveibeenpwned), a little more documentation would be nice. "Go See Github" works for developers (it did for me), but being able to read more about it on the marketplace just helps make it more trustworthy.

Nice work, thanks for developing! I may drop it in to a few of my Bolt sites to play with it.

**Comment by michaelborn** [comment]
Also, feel free to delete this to pieces, cuz it's not really an issue...

**Comment by scotteuser** [comment]
Thanks for trying it out and for the feedback! Makes sense, I'll put more details on the market page.

Yeah it is fun to play with even just to be amazed at how many times password123 has been in a known breach + of course handy if you have non technical users who have lazy password attitudes :) Forces them to be a bit better at least!

**Comment by michaelborn** [comment]
Lol - "non technical users" ... did you mean to say "all users"? ;)
